ExchangeRates/Models/EnumExtensions.cs
using System;
using System.Linq;
using System.Web.Mvc;

namespace ExchangeRates.Models
{
    public static class EnumExtensions
    {
        public static SelectList ToSelectList<TEnum>(this TEnum enumObj)
            where TEnum : struct, IComparable, IFormattable, IConvertible
        {
            var values = from TEnum e in Enum.GetValues(typeof(TEnum))
                select new { Id = e, Name = e.ToString() };
            return new SelectList(values, "Id", "Name", enumObj);
        }
    }
}

ExchangeRates/Models/Exceptions/FailToResolveViewModelException.cs
using System;

namespace ExchangeRates.Models.Exceptions
{
    public class FailToResolveViewModelException : ApplicationException
    {
        public FailToResolveViewModelException(Exception ex)
            :base("Error: Fail to resolve viewmodel from dependency root", ex)
        {
            
        }
    }
}

ExchangeRates/Models/Exceptions/UnexpectedViewModelException.cs
using System;

namespace ExchangeRates.Models.Exceptions
{
    public class UnexpectedViewModelException : ApplicationException
    {
        public UnexpectedViewModelException(Exception ex)
            : base("Error: unexpected viewmodel exception", ex)
        {

        }
    }
}

ExchangeRates/Models/ExchangeRatesVm.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;
using ExchangeRates.BL.Interface;
using ExchangeRetes.DM;

namespace ExchangeRates.Models
{
    /// <summary>
    /// ViewModel, that provides exchange rates reports data by date interval and currency
    /// </summary>
    public class ExchangeRatesVm
    {
        /// <summary>
        /// Provider of exchange rates data
        /// </summary>
        private readonly IExchangeRates _exchangeRates;

        /// <summary>
        /// Constructs example of <see cref="ExchangeRatesVm"/>
        /// </summary>
        /// <param name="exchangeRates">Provider of exchange rates data</param>
        /// <exception cref="ArgumentNullException"/>
        public ExchangeRatesVm(IExchangeRates exchangeRates)
        {
            if (exchangeRates == null) 
                throw new ArgumentNullException("exchangeRates");
            _exchangeRates = exchangeRates;
            IsSuccesfull = true;
            ErrorMessage = string.Empty;
            Currency = Currency.RUB;
            StartDate = DateTime.Today.AddDays(-10);
            EndDate = DateTime.Today;
            CurrencyList = Currency.RUB.ToSelectList();
        }
        

        #region Input

        public SelectList CurrencyList { get; set; }

        [Display(Name = "Start date")]
        [Required(ErrorMessage = "Enter currency")]
        public Currency Currency { get; set; }

        [Display(Name = "End date")]
        [Required(ErrorMessage = "Enter start date")]
        [DisplayFormat(DataFormatString = "{0:dd.MM.yyyy}")]
        public DateTime? StartDate { get; set; }

        [Display(Name = "Currency")]
        [Required(ErrorMessage = "Enter end date")]
        [DisplayFormat(DataFormatString = "{0:dd.MM.yyyy}")]
        public DateTime? EndDate { get; set; }
        
        #endregion


        #region Output

        /// <summary>
        /// Result rate list
        /// </summary>
        public IList<Rate> Rates { get; set; }

        /// <summary>
        /// Returns true if <see cref="GetRates"/> was performed without error
        /// </summary>
        public bool IsSuccesfull { get; set; }

        /// <summary>
        /// Some error information about <see cref="GetRates"/> performing
        /// </summary>
        public string ErrorMessage { get; set; }

        /// <summary>
        /// Provides rate list to the <see cref="Rates"/> using input <see cref="StartDate"/>, <see cref="EndDate"/> and <see cref="Currency"/>
        /// </summary>
        public void GetRates()
        {
            try
            {
                if (!StartDate.HasValue)
                {
                    throw new ApplicationException("Error: Start date must have value");
                }

                if (!EndDate.HasValue)
                {
                    throw new ApplicationException("Error: End date must have value");
                }

                // Getting rates here
                Rates = _exchangeRates.GetRates(Currency, StartDate.Value, EndDate.Value);

                if (string.IsNullOrEmpty(_exchangeRates.ErrorMessage))
                {
                    IsSuccesfull = true;
                    ErrorMessage = string.Empty;
                }
                else
                {
                    IsSuccesfull = false;
                    ErrorMessage = _exchangeRates.ErrorMessage;
                }
            }
            catch (ApplicationException ex)
            {
                IsSuccesfull = false;
                ErrorMessage = string.Format(ex.Message);

            }
            catch (Exception ex)
            {
                IsSuccesfull = false;
                ErrorMessage = string.Format("Unexpected error: {0}", ex);

            }
        }

        /// <summary>
        /// Returns strigified view of input date interval days.
        /// </summary>
        public string GetDays()
        {
            if (Rates != null)
            {
                string result = string.Empty;
                foreach (var rate in Rates)
                {
                    result += string.Format("'{0}',", rate.Stamp.ToString("yyyy-MM-dd"));
                }
                return result.Substring(0, result.Length - 1);
            }
            return string.Empty;
        }

        /// <summary>
        /// Returns strigified view of result rates.
        /// </summary>
        public string GetRatesData()
        {
            if (Rates != null)
            {
                string result = string.Empty;
                foreach (var rate in Rates)
                {
                    result += string.Format("['{0}',{1}],", rate.Stamp.ToString("yyyy-MM-dd"), rate.Value.ToString("F6").Replace(',','.'));
                }

                return result.Substring(0, result.Length - 1);
            }
            return string.Empty;
        }

        #endregion
    }
}

ExchangeRates/Controllers/ExchangeRateController.cs
using System.Web.Mvc;
using ExchangeRates.Models;

namespace ExchangeRates.Controllers
{
    /// <summary>
    /// Controller, that provide exchange rates reports
    /// </summary>
    public class ExchangeRateController : Controller
    {
        /// <summary>
        /// Shows form for exchange rates request
        /// </summary>
        [HttpGet]
        public ActionResult Index(ExchangeRatesVm exchangeRatesVm)
        {
            return View("Index", exchangeRatesVm);
        }

        /// <summary>
        /// Shows exchange rates report
        /// </summary>
        [HttpPost]
        public ActionResult Rate(ExchangeRatesVm exchangeRatesVm)
        {
            if (!ModelState.IsValid)
            {
                return View("Index", exchangeRatesVm);
            }

            exchangeRatesVm.GetRates();

            if (!exchangeRatesVm.IsSuccesfull)
            {
                ModelState.AddModelError(string.Empty, exchangeRatesVm.ErrorMessage);
            }

            return View("Index", exchangeRatesVm);
        }

    }
}

ExchangeRates/Views/ExchangeRate/Index.cshtml
@model ExchangeRates.Models.ExchangeRatesVm
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("Rate", "ExchangeRate", FormMethod.Post, new { @class = "navbar-form" }))
{
    <h4>Exchange Rate</h4>
    <fieldset class="form-horizontal">
        <div class="pull-left form-edit">
            @Html.LabelFor(m => m.StartDate)
            @Html.EditorFor(m => m.StartDate)
            @Html.ValidationMessageFor(m => m.StartDate)
        </div>
        <div class="pull-left form-edit">
            @Html.LabelFor(m => m.EndDate)
            @Html.EditorFor(m => m.EndDate)
            @Html.ValidationMessageFor(m => m.EndDate)
        </div>
        <div class="pull-left form-edit">
            @Html.LabelFor(m => m.Currency)
            @Html.DropDownListFor(m => m.Currency, Model.CurrencyList)
            @Html.ValidationMessageFor(m => m.Currency)
        </div>
        <div class="clearfix"></div>
    </fieldset>
    @Html.ValidationSummary(true)
    <button type="submit" class="btn btn-primary">Show</button>
}

@if (Model.Rates != null)
{
    <script type='text/javascript'>
        $(window).load(function () {
            $(function () {
                $('#container').highcharts({
                    title: {
                        text: '@Model.Currency.ToString()/USD rates'
                    },
                    xAxis: {
                        labels :
                        {
                            rotation: -90
                        }
                        ,
                        categories: [@Html.Raw(Model.GetDays())]
                    },
                    yAxis: {
                        title: {
                            text: '@Model.Currency.ToString() for USD'
                        }
                    },
                    series: [{
                        name: '@Model.Currency.ToString()',
                        data: [@Html.Raw(Model.GetRatesData())]
                    }]
                });
            });

        });
    </script>

    <script src="http://code.highcharts.com/highcharts.js"></script>
    <script src="http://code.highcharts.com/modules/exporting.js"></script>

    <div id="container" style="width: 100%; height: 400px;"></div>
}

ExchangeRates/Views/Shared/EditorTemplates/DateTime.cshtml
@model DateTime?
@Html.TextBoxFor(m => m, new { @class = "datepicker", @Value = Model.HasValue ? Model.Value.ToString("d") : null })

ExchangeRates/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>ExchangeRates</title>
    <meta name="viewport" content="width=device-width" />
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.9.1/jquery-ui.min.js"></script>
    <script type="text/javascript" src="//netdna.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js"></script>
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css" rel="stylesheet">
    <link href="//code.jquery.com/ui/1.10.4/themes/smoothness/jquery-ui.css" rel="stylesheet">
    <link href="../../Content/layout.css" rel="stylesheet">
    <script>
        $(function () {
            $(".datepicker").datepicker({ dateFormat: "dd.mm.yy" });
        });
  </script>
</head>

<body>

    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <a class="navbar-brand" href="#">ExchangeRates</a>
            </div>
        </div>
    </div>
    <div id="wrap">
        <div class="container">
            @RenderBody()
        </div>
        <div id="push"></div>
    </div>

    <div id="footer">
        <div class="container">
            Kozhevnikov Dmitry, <a href="mailto:d.o.kozhevnikov@gmail.com">d.o.kozhevnikov@gmail.com</a>
        </div>
    </div>

</body>
</html>